name: Java CI and Manual Run

on:
  push:
    branches: [ "main" ]    # or the branch you want to monitor
  workflow_dispatch:        # allows manual runs in GitHub Actions

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2
      
      # 2) Set up Java (here using Java 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3) Build the project and download dependencies
      - name: Build with Maven
        run: mvn clean install

      # 4) Run unit tests
      - name: Run tests
        run: mvn test

      # 5) Update code in the repository (e.g., append a timestamp to a log file)
      - name: Commit and push changes
        run: |
          echo "Automated workflow run at $(date)" >> ci-run.log
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ci-run.log
          
          # If there's nothing new to commit, the next command will fail.
          git commit -m "Add timestamp: $(date)" || echo "Nothing to commit."
          
          # Attempt to push. If no commit was made, nothing will happen.
          git push origin HEAD:${{ github.ref }}
